# Generated by Django 4.1 on 2022-09-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_pagehit_alter_post_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageHit',
        ),
    ]
